### ISSUE TITLE
Errors when using trainingland dataset

### ISSUE THREAD

**Issue by rrowlands** [pgracio/dhis2-docker#14]
I had some issues when using the trainingland dataset. The webapp startup context listener failed during its database task. Log is attached.
[dhis2-web-trainingland.txt](https://github.com/pgracio/dhis2-docker/files/627997/dhis2-web-trainingland.txt)

The database sql import completed without errors.

**Comment by pgracio** [comment]
Hi @rrowlands which versions are you trying to use? I don't think trainingland dataset works with latest versions, only 2.20 and 2.21.

**Comment by rrowlands** [comment]
Yeah I tried it on 2.25.
