### ISSUE TITLE
no data visible

### ISSUE THREAD

**Issue by jpainter** [pgracio/dhis2-docker#18]
After logging into the dhis2 sierra leone app created with the stackfile, no data appears in the app.  The organization units and data elements are visible, but no data.  Is there a setting to make it visible?  PS.  Thanks for creating this docker image--it will be very helpful.

**Comment by jason-p-pickering** [comment]
@jpainter You need to run analytics. 

 See our FAQ. 

https://docs.dhis2.org/master/en/user/html/ch32.html

**Comment by jpainter** [comment]
Yes, that was it. Thanks very much!


John Painter, DVM, MS
Surveillance, Monitoring, and Evaluation Team Lead
CDC-President’s Malaria Initiative,
Malaria Branch,
Division of Parasitic Diseases and Malaria,
US Centers for Disease Control and Prevention,
Atlanta, GA
Mailstop A-06
