### ISSUE TITLE
Update war file

### ISSUE THREAD

**Issue by jotasolano** [pgracio/dhis2-docker#19]
Hello.

Is there a way we can update the war file within the docker image? An important bug has just been fixed ([oAuth for the API was broken](https://jira.dhis2.org/browse/DHIS2-1862)) and we would like to update the war file to the latest version from the continuous integration service. 

Thanks.

**Comment by jason-p-pickering** [comment]
You can build it yourself with the docker code in this repo, or wait for the nightly builds which get pushed to DockerHub.

**Comment by jotasolano** [comment]
Thanks for the quick reply
