### ISSUE TITLE
No data display on the dashbord

### ISSUE THREAD

**Issue by zhangyewu** [pgracio/dhis2-docker#20]
I have deployed his2-docker on my computer. The apps for data entry, event caputure worked fine, but the apps for data analysis and visualization seemed not to be able to get access to the data in dhis2-database. No data display on the dashboard. would you please figure out these problems?
![2017-08-31_103307](https://user-images.githubusercontent.com/71384/29903724-dfb33646-8e37-11e7-8610-2967c3bcdcee.png)

**Comment by jason-p-pickering** [comment]
@zhangyewu please have a look at our FAQ. 

You need to run analytics.

https://docs.dhis2.org/master/en/user/html/ch32.html

Duplicate of #18

**Comment by zhangyewu** [comment]
It works. Thank you very much!
