### ISSUE TITLE
problems with container

### ISSUE THREAD

**Issue by baradhili** [pgracio/dhis2-docker#23]
Hi, I'm new to Docker, so might have stuffed this up but...
`ERROR: for database  Cannot start service database: driver failed programming external connectivity on endpoint dhis2-database (316ee409ab67dcaeca1f042a38558381be092bc8d4a6a99af11a17dffec319ae): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use`

Is what I am getting when I run `sudo docker-compose up -d`

`sudo docker-compose logs -f`
Attaching to dhis2-database
dhis2-database exited with code 128

I don't have any containers up and running 

Thanks

**Comment by pgracio** [comment]
Hi @baradhili are you still having issues with this?

**Comment by baradhili** [comment]
I forgot about this.. no I gave up :)

**Comment by pgracio** [comment]
Ok. The error mentions that port 5432 was already being used by another process. Maybe a local postgres instance running.
