### ISSUE TITLE
Getting exception when opening Tracker Capture

### ISSUE THREAD

**Issue by adam704a** [pgracio/dhis2-docker#3]
Here is the exception:

web_1 | \* INFO  2015-04-23 18:20:21,685 Login success for user: 'admin', ip: '192.168.59.3' (DefaultUserAuditService.java [http-bio-8080-exec-1])
web_1 | \* ERROR 2015-04-23 18:20:44,651 Error while executing action (ExceptionInterceptor.java [http-bio-8080-exec-4])
web_1 | org.hibernate.NonUniqueResultException: query did not return a unique result: 2
web_1 |     at org.hibernate.internal.AbstractQueryImpl.uniqueElement(AbstractQueryImpl.java:914)
web_1 |     at org.hibernate.internal.CriteriaImpl.uniqueResult(CriteriaImpl.java:396)
web_1 |     at org.hisp.dhis.version.hibernate.HibernateVersionStore.getVersionByKey(HibernateVersionStore.java:43)
web_1 |     at org.hisp.dhis.version.DefaultVersionService.getVersionByKey(Defa

On the page it just says: "Loading meta-data"

**Comment by pgracio** [comment]
Hi,
this is a problem in DHIS2 itself, I have sent an email reporting these problem to dhis2-users.

thanks for having reported the problem.

/Paulo

**Comment by pgracio** [comment]
@adam704a answer from dhis2 community was 

> Hi, Go to your version table, and remove one (or both) of the entries with versionkey organisationUnit.
> Morten

**Comment by adam704a** [comment]
I am still getting the error.  I found that after I added an organization unit (though the UI) everything worked.  I'll add this to the launchpad discussion as well.

**Comment by pgracio** [comment]
Hi, @adam704a you can see all the emails here
https://lists.launchpad.net/dhis2-users/msg07027.html

Image it's not updated with the fix that Lars mentioned. Will try to do that asap.

**Comment by adam704a** [comment]
Lars's suggestion didn't work for me, but what did was just adding a root organizational unit. I'll post this on the launchpad site.

**Comment by pgracio** [comment]
@adam704a latest image has this problem fixed.
