### ISSUE TITLE
Tuntum is closed for account registration

### ISSUE THREAD

**Issue by dawoodjee** [pgracio/dhis2-docker#5]
Tuntum is closed for account registration, the Readme requires update.

**Comment by pgracio** [comment]
Hi @adam-je, thanks for your feedback. Tutum was acquired by Docker and is now called Docker Cloud. If you want to register you can do it here https://cloud.docker.com/

**Comment by pgracio** [comment]
I have also create a PR #6, please try to follow the steps mentioned there.
